steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - asia-southeast2-docker.pkg.dev/juaravibecoding-337f9/cloud-run-source-deploy/sales-hub-web:latest
      - --build-arg
      - NEXT_PUBLIC_API_URL=https://sales-hub-api-plybi3wglq-et.a.run.app
      - --build-arg
      - NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyASFiLs-5AHTAZdjthigDjLLXFTx-w8TUg
      - --build-arg
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=juaravibecoding-337f9.firebaseapp.com
      - --build-arg
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID=juaravibecoding-337f9
      - --build-arg
      - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=22923549407
      - --build-arg
      - NEXT_PUBLIC_FIREBASE_APP_ID=1:22923549407:web:6206a9907e32787442276a
      - --build-arg
      - NEXT_PUBLIC_FIREBASE_VAPID_KEY=BEHBmkCBykL0eiPzhd42YNnZAlmTxNZtxzAzfVZwhq6a20No5lEUt9zPaxtufp13Kj55qlK6sRYX5lKYmjUYRBg
      - .

images:
  - asia-southeast2-docker.pkg.dev/juaravibecoding-337f9/cloud-run-source-deploy/sales-hub-web:latest
